import { Fragment, useState } from 'react';
import { 
  FileText, 
  Upload, 
  X, 
  Eye, 
  Download, 
  Save, 
  RotateCcw,
  Settings,
  Image as ImageIcon,
  Type,
  AlignLeft,
  Building,
  CheckCircle,
  AlertCircle
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { 
  Select, 
  SelectContent, 
  SelectItem, 
  SelectTrigger, 
  SelectValue 
} from '@/components/ui/select';
import { Switch } from '@/components/ui/switch';
import { Badge } from '@/components/ui/badge';
import { PDFPreviewModal } from './PDFPreviewModal';

const PDFConfigurationContent = () => {
  const [formData, setFormData] = useState({
    headerTitle: 'Service Report',
    footerText: 'This report is generated by ServiceOn. All rights reserved. For questions, contact support@serviceon.com',
    logo: null as File | null,
    signaturePlacement: 'bottom-right',
    applyToAllGarages: false,
    version: '1.0'
  });

  const [logoPreview, setLogoPreview] = useState<string | null>(null);
  const [showPreview, setShowPreview] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  const [hasChanges, setHasChanges] = useState(false);

  const handleInputChange = (field: string, value: string | boolean) => {
    setFormData(prev => ({
      ...prev,
      [field]: value
    }));
    setHasChanges(true);
  };

  const handleLogoUpload = (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (file) {
      setFormData(prev => ({
        ...prev,
        logo: file
      }));
      
      // Create preview
      const reader = new FileReader();
      reader.onload = (e) => {
        setLogoPreview(e.target?.result as string);
      };
      reader.readAsDataURL(file);
      setHasChanges(true);
    }
  };

  const removeLogo = () => {
    setFormData(prev => ({
      ...prev,
      logo: null
    }));
    setLogoPreview(null);
    setHasChanges(true);
  };

  const handlePreview = () => {
    setShowPreview(true);
  };

  const handleDownload = () => {
    console.log('Download PDF sample');
  };

  const handleSave = async () => {
    setIsSaving(true);
    try {
      // Simulate API call
      await new Promise(resolve => setTimeout(resolve, 2000));
      console.log('Saving PDF configuration:', formData);
      setHasChanges(false);
    } catch (error) {
      console.error('Save failed:', error);
    } finally {
      setIsSaving(false);
    }
  };

  const handleReset = () => {
    setFormData({
      headerTitle: 'Service Report',
      footerText: 'This report is generated by ServiceOn. All rights reserved. For questions, contact support@serviceon.com',
      logo: null,
      signaturePlacement: 'bottom-right',
      applyToAllGarages: false,
      version: '1.0'
    });
    setLogoPreview(null);
    setHasChanges(false);
  };

  const signaturePlacementOptions = [
    { value: 'bottom-left', label: 'Bottom Left' },
    { value: 'bottom-right', label: 'Bottom Right' },
    { value: 'bottom-center', label: 'Bottom Center' },
    { value: 'top-right', label: 'Top Right' }
  ];

  return (
    <Fragment>
      <div className="space-y-6">
        {/* Header */}
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-2xl font-bold text-gray-900 dark:text-white">PDF Configuration</h1>
            <p className="text-gray-600 dark:text-gray-400">Configure PDF templates and branding settings</p>
          </div>
          <div className="flex items-center gap-2">
            <Badge className="bg-blue-100 text-blue-800 dark:bg-blue-900 dark:text-blue-200">
              Version {formData.version}
            </Badge>
            {hasChanges && (
              <Badge className="bg-orange-100 text-orange-800 dark:bg-orange-900 dark:text-orange-200">
                Unsaved Changes
              </Badge>
            )}
          </div>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          {/* Main Configuration */}
          <div className="lg:col-span-2 space-y-6">
            {/* Header Settings */}
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <Type className="h-5 w-5" />
                  Header Configuration
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="space-y-2">
                  <Label htmlFor="headerTitle">Header Title *</Label>
                  <Input
                    id="headerTitle"
                    value={formData.headerTitle}
                    onChange={(e) => handleInputChange('headerTitle', e.target.value)}
                    placeholder="Enter header title"
                    required
                  />
                  <p className="text-xs text-gray-500">
                    This will appear at the top of all PDF documents
                  </p>
                </div>

                <div className="space-y-2">
                  <Label htmlFor="footerText">Footer Text (Legal Text) *</Label>
                  <Textarea
                    id="footerText"
                    value={formData.footerText}
                    onChange={(e) => handleInputChange('footerText', e.target.value)}
                    placeholder="Enter footer text"
                    rows={3}
                    required
                  />
                  <p className="text-xs text-gray-500">
                    Legal disclaimer or company information that appears at the bottom
                  </p>
                </div>
              </CardContent>
            </Card>

            {/* Logo Upload */}
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <ImageIcon className="h-5 w-5" />
                  Logo Configuration
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="space-y-4">
                  {logoPreview ? (
                    <div className="relative">
                      <img
                        src={logoPreview}
                        alt="Logo preview"
                        className="w-full h-32 object-contain border rounded-lg"
                      />
                      <Button
                        type="button"
                        variant="destructive"
                        size="sm"
                        className="absolute top-2 right-2"
                        onClick={removeLogo}
                      >
                        <X className="h-4 w-4" />
                      </Button>
                    </div>
                  ) : (
                    <div className="border-2 border-dashed border-gray-300 rounded-lg p-6 text-center">
                      <Upload className="h-8 w-8 mx-auto text-gray-400 mb-2" />
                      <p className="text-sm text-gray-500">Upload company logo</p>
                      <p className="text-xs text-gray-400">PNG, JPG up to 2MB</p>
                    </div>
                  )}

                  <div>
                    <Label htmlFor="logo" className="cursor-pointer">
                      <div className="flex items-center justify-center w-full p-2 border border-gray-300 rounded-lg hover:bg-gray-50 dark:hover:bg-gray-800">
                        <Upload className="h-4 w-4 mr-2" />
                        Choose Logo File
                      </div>
                    </Label>
                    <Input
                      id="logo"
                      type="file"
                      accept="image/*"
                      onChange={handleLogoUpload}
                      className="hidden"
                    />
                  </div>

                  <div className="text-xs text-gray-500">
                    <p>• Recommended size: 200x100px</p>
                    <p>• Supported formats: PNG, JPG</p>
                    <p>• Max file size: 2MB</p>
                  </div>
                </div>
              </CardContent>
            </Card>

            {/* Signature Settings */}
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <AlignLeft className="h-5 w-5" />
                  Signature Configuration
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="space-y-2">
                  <Label htmlFor="signaturePlacement">Signature Placement</Label>
                  <Select 
                    value={formData.signaturePlacement} 
                    onValueChange={(value) => handleInputChange('signaturePlacement', value)}
                  >
                    <SelectTrigger>
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      {signaturePlacementOptions.map((option) => (
                        <SelectItem key={option.value} value={option.value}>
                          {option.label}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                  <p className="text-xs text-gray-500">
                    Choose where the digital signature will be placed on the PDF
                  </p>
                </div>
              </CardContent>
            </Card>

            {/* Global Settings */}
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <Settings className="h-5 w-5" />
                  Global Settings
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="flex items-center justify-between">
                  <div>
                    <Label htmlFor="applyToAllGarages">Apply to All Garages</Label>
                    <p className="text-sm text-gray-500">Use this template for all garage locations</p>
                  </div>
                  <Switch
                    id="applyToAllGarages"
                    checked={formData.applyToAllGarages}
                    onCheckedChange={(checked) => handleInputChange('applyToAllGarages', checked)}
                  />
                </div>
              </CardContent>
            </Card>
          </div>

          {/* Preview Sidebar */}
          <div className="space-y-6">
            {/* PDF Preview */}
            <Card>
              <CardHeader>
                <CardTitle>PDF Preview</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="space-y-4">
                  <div className="border rounded-lg p-4 bg-gray-50 dark:bg-gray-800">
                    <div className="flex items-center justify-between mb-3">
                      <div className="font-medium text-sm">
                        {formData.headerTitle || 'Service Report'}
                      </div>
                      {logoPreview && (
                        <img
                          src={logoPreview}
                          alt="Logo"
                          className="h-6 w-auto object-contain"
                        />
                      )}
                    </div>
                    <div className="text-xs text-gray-500 mb-3">
                      Sample PDF content will appear here...
                    </div>
                    <div className="text-xs text-gray-400 border-t pt-2">
                      {formData.footerText || 'Footer text...'}
                    </div>
                  </div>
                  
                  <div className="space-y-2">
                    <Button 
                      onClick={handlePreview}
                      className="w-full flex items-center gap-2"
                    >
                      <Eye className="h-4 w-4" />
                      Preview PDF
                    </Button>
                    <Button 
                      variant="outline"
                      onClick={handleDownload}
                      className="w-full flex items-center gap-2"
                    >
                      <Download className="h-4 w-4" />
                      Download Sample
                    </Button>
                  </div>
                </div>
              </CardContent>
            </Card>

            {/* Version Info */}
            <Card>
              <CardHeader>
                <CardTitle>Template Information</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="space-y-3 text-sm">
                  <div className="flex justify-between">
                    <span className="text-gray-500">Version:</span>
                    <span className="font-medium">v{formData.version}</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-gray-500">Last Updated:</span>
                    <span>Jan 15, 2024</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-gray-500">Status:</span>
                    <Badge className="bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-200">
                      Active
                    </Badge>
                  </div>
                </div>
              </CardContent>
            </Card>

            {/* Actions */}
            <Card>
              <CardHeader>
                <CardTitle>Actions</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="space-y-2">
                  <Button 
                    onClick={handleSave}
                    disabled={isSaving || !hasChanges}
                    className="w-full flex items-center gap-2"
                  >
                    <Save className="h-4 w-4" />
                    {isSaving ? 'Saving...' : 'Save Changes'}
                  </Button>
                  <Button 
                    variant="outline"
                    onClick={handleReset}
                    disabled={isSaving}
                    className="w-full flex items-center gap-2"
                  >
                    <RotateCcw className="h-4 w-4" />
                    Reset
                  </Button>
                </div>
              </CardContent>
            </Card>
          </div>
        </div>
      </div>

      {/* PDF Preview Modal */}
      <PDFPreviewModal 
        open={showPreview}
        onOpenChange={setShowPreview}
        config={formData}
      />
    </Fragment>
  );
};

export { PDFConfigurationContent };

